//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace poyecto_catedra_poo_supermecado.Conexion
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_supermercadoEntities : DbContext
    {
        public db_supermercadoEntities()
            : base("name=db_supermercadoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_carrito> tb_carrito { get; set; }
        public virtual DbSet<tb_categorias> tb_categorias { get; set; }
        public virtual DbSet<tb_distribuidores> tb_distribuidores { get; set; }
        public virtual DbSet<tb_producto> tb_producto { get; set; }
        public virtual DbSet<tb_promociones> tb_promociones { get; set; }
        public virtual DbSet<tb_usario> tb_usario { get; set; }
        public virtual DbSet<tb_ventas> tb_ventas { get; set; }
    }
}
