//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace poyecto_catedra_poo_supermecado.Conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_carrito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_carrito()
        {
            this.tb_ventas = new HashSet<tb_ventas>();
        }
    
        public int id_carrito { get; set; }
        public Nullable<decimal> precio_total { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string estado { get; set; }
        public Nullable<int> id_prod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ventas> tb_ventas { get; set; }
        public virtual tb_producto tb_producto { get; set; }
    }
}
