//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace poyecto_catedra_poo_supermecado.Conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_detalle_venta
    {
        public int id_detalle { get; set; }
        public Nullable<int> id_venta { get; set; }
        public Nullable<int> id_producto { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> precio_unitario { get; set; }
        public Nullable<decimal> descuento_aplicado { get; set; }
        public Nullable<decimal> subtotal { get; set; }
    
        public virtual tb_producto tb_producto { get; set; }
        public virtual tb_ventas tb_ventas { get; set; }
    }
}
