//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace poyecto_catedra_poo_supermecado.Conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_producto()
        {
            this.tb_carrito = new HashSet<tb_carrito>();
        }
    
        public int id_prod { get; set; }
        public string nombre { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<int> stock { get; set; }
        public byte[] imangen { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> id_distriubidores { get; set; }
        public Nullable<int> id_categoria { get; set; }
        public Nullable<int> id_prom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_carrito> tb_carrito { get; set; }
        public virtual tb_categorias tb_categorias { get; set; }
        public virtual tb_distribuidores tb_distribuidores { get; set; }
        public virtual tb_promociones tb_promociones { get; set; }
    }
}
