//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace poyecto_catedra_poo_supermecado.Conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ventas
    {
        public int id_ventas { get; set; }
        public string nombre_cliente { get; set; }
        public Nullable<int> id_carrito { get; set; }
        public Nullable<int> id_usuario { get; set; }
    
        public virtual tb_carrito tb_carrito { get; set; }
        public virtual tb_usario tb_usario { get; set; }
    }
}
