//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace poyecto_catedra_poo_supermecado.Conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ventas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_ventas()
        {
            this.tb_detalle_venta = new HashSet<tb_detalle_venta>();
        }
    
        public int id_venta { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string nombre_cliente { get; set; }
        public Nullable<decimal> total_venta { get; set; }
        public Nullable<decimal> total_descuento { get; set; }
        public string estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_detalle_venta> tb_detalle_venta { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
