//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace poyecto_catedra_poo_supermecado.Conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_detalle_ventas_completo
    {
        public int id_venta { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string nombre_cliente { get; set; }
        public Nullable<int> id_cajero { get; set; }
        public string cajero { get; set; }
        public string producto { get; set; }
        public string categoria { get; set; }
        public string distribuidor { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> precio_unitario { get; set; }
        public Nullable<decimal> descuento_aplicado { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public string estado { get; set; }
    }
}
